### ISSUE TITLE
New vite 6.0.2 causing dependency error of vite-plugin-inspect in Nuxt appliaction

### ISSUE THREAD

**Issue by filius-fall** [antfu-collective/vite-plugin-inspect#122]
### Describe the bug

After doing 
npx nuxi@latest init <project-name>
npm install
npm run dev

vite-plugin-inspect is throwing the error.
when checked the package-lock.json the vite version in peerDependencies is 6.0.2
### Reproduction

in package-lock.json change peerDependencies changing the version of vite to 6.0.2 will show the error 
However when changed back to 5.4.11 it doesnt give any error

### System Info

```Shell
When using npm run dev after installing nuxt it is throwing error 
Cannot start nuxt:  Cannot convert undefined or null to object                                                                                                                                 4:04:31 pm

  at Function.values (<anonymous>)
  at configureServer (node_modules/vite-plugin-inspect/dist/index.mjs:1410:12)
  at configureServer (node_modules/vite-plugin-inspect/dist/index.mjs:1496:19)
  at _createServer (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:26)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.B69gK6ir.mjs:733:24)
  at async withLogs (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.B69gK6ir.mjs:1781:3)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.B69gK6ir.mjs:1772:3)
  at async bundle (node_modules/nuxt/dist/index.mjs:6091:5)
  at async build (node_modules/nuxt/dist/index.mjs:5966:3)
  at async Promise.all (index 1)

when we use vite 6.0.2 version, but when reverted to vite 5.4.2 the vite-plugin-inspector issue not shown
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Reported in https://github.com/nuxt/nuxt/issues/30127, it's a bug introduced by Nuxt DevTools, not this plugin.
